/* Copyright (c) 2000-2007 Wolfgang Hoermann and Josef Leydold */
/* Department of Statistics and Mathematics, WU Wien, Austria  */

#ifndef UNUR_STDDISTR_H_SEEN
#define UNUR_STDDISTR_H_SEEN
enum {
  UNUR_DISTR_GENERIC  = 0x0u,
  UNUR_DISTR_CORDER,              
  UNUR_DISTR_CXTRANS,             
  UNUR_DISTR_CONDI,               
  UNUR_DISTR_BETA,                
  UNUR_DISTR_CAUCHY,              
  UNUR_DISTR_CHI,                 
  UNUR_DISTR_CHISQUARE,           
  UNUR_DISTR_EPANECHNIKOV,        
  UNUR_DISTR_EXPONENTIAL,         
  UNUR_DISTR_EXTREME_I,           
  UNUR_DISTR_EXTREME_II,          
  UNUR_DISTR_F,                   
  UNUR_DISTR_GAMMA,               
  UNUR_DISTR_GIG,                 
  UNUR_DISTR_LAPLACE,             
  UNUR_DISTR_LOGISTIC,            
  UNUR_DISTR_LOGNORMAL,           
  UNUR_DISTR_LOMAX,               
  UNUR_DISTR_NORMAL   = 0x0100u,  
   UNUR_DISTR_GAUSSIAN = 0x0100u, 
  UNUR_DISTR_PARETO,              
  UNUR_DISTR_POWEREXPONENTIAL,    
  UNUR_DISTR_RAYLEIGH,            
  UNUR_DISTR_SLASH,               
  UNUR_DISTR_STUDENT,             
  UNUR_DISTR_TRIANGULAR,          
  UNUR_DISTR_UNIFORM = 0x0200u,   
   UNUR_DISTR_BOXCAR = 0x0200u,   
  UNUR_DISTR_WEIBULL,             
  UNUR_DISTR_BURR_I,              
  UNUR_DISTR_BURR_II,             
  UNUR_DISTR_BURR_III,            
  UNUR_DISTR_BURR_IV,             
  UNUR_DISTR_BURR_V,              
  UNUR_DISTR_BURR_VI,             
  UNUR_DISTR_BURR_VII,            
  UNUR_DISTR_BURR_VIII,           
  UNUR_DISTR_BURR_IX,             
  UNUR_DISTR_BURR_X,              
  UNUR_DISTR_BURR_XI,             
  UNUR_DISTR_BURR_XII,            
  UNUR_DISTR_BINOMIAL,            
  UNUR_DISTR_GEOMETRIC,           
  UNUR_DISTR_HYPERGEOMETRIC,      
  UNUR_DISTR_LOGARITHMIC,         
  UNUR_DISTR_NEGATIVEBINOMIAL,    
  UNUR_DISTR_POISSON,             
  UNUR_DISTR_ZIPF,                
  UNUR_DISTR_MCAUCHY,             
  UNUR_DISTR_MNORMAL,             
  UNUR_DISTR_MSTUDENT,            
  UNUR_DISTR_MEXPONENTIAL,        
  UNUR_DISTR_COPULA,              
  UNUR_DISTR_MCORRELATION         
};
#endif  
